import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { cn } from "@/lib/utils";
import FirstNav from "./_components/FirstNav/FirstNav";
import FeaturesSection from "./_components/FeaturesSection/FeaturesSection";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import MyProvider from "./_components/MyProvider/MyProvider";
import { AppProvider } from './../context/AppContext';
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce APP",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <MyProvider>
        <AppProvider>
          <FirstNav />
          <Navbar />
          {children}
          <Toaster position="top-right" />
          <FeaturesSection />
          <Footer />
        </AppProvider>
        </MyProvider>
      </body>
    </html>
  );
}
